### ISSUE TITLE
Warning for unused variable on vlogger.cpp

### ISSUE THREAD

**Issue by mrseth** [vitimiti/MatVG#3]
[code]
/home/sergio/Repositories/MatVG/MatVGL/src/gnu/vlogger.cpp:140:20: error: variable ‘logger’ set but not used [-Werror=unused-but-set-variable]
   matvgl::vlogger *logger = nullptr;
                    ^
cc1plus: all warnings being treated as errors
make[2]: *** [MatVGL/CMakeFiles/matvg-logger.dir/src/gnu/vlogger.cpp.o] Error 1
make[1]: *** [MatVGL/CMakeFiles/matvg-logger.dir/all] Error 2
[/code]

You put a comment about warnings, but it is throwing a warning regardless. Adding a if(logger) removes the warning, but you should consider refactoring this part or adding a //TODO indicating its a placeholder.

**Comment by mrseth** [comment]
Oh, and consider lowering requirement for cmake version, ubuntu 14.something ships with 2.8 and you require 3.something.

**Comment by vitimiti** [comment]
I checked your warning, and it appears that, while clang doesn't through it, GCC does through it, so your issue will be taken into consideration. I will also consider lowering cmake to 2.8, since as of now I'm not using any 3.0 or over functionality.
